### PR TITLE
Windows: use libtiff 4.1.0

### PR DESCRIPTION
**Pull request by jeroen**
This fixes the CRAN problems. I built some fresh libs for the latest libtiff 4.1.0. 

These libs work both with the gcc-4.9 toolchain (for R 3.6 and older) as well as the new gcc-8 toolchain for R 4.0 and up.

Winbuilder test results:

 - R-3.6.3 (oldrel): https://win-builder.r-project.org/jn0L7N6lmk5d
 - R-devel: https://win-builder.r-project.org/9aSb3G85xJV4

### CODE REVIEW

**Comment by jeroen** [comment]
@s-u could you consider merging this and sending it to CRAN? That way other packages that depend on tiff will working on R 4.0+. We are using these same builds now in the [ijtiff](https://cran.r-project.org/web/packages/ijtiff/index.html) package and it has solved all the problems.

**Review by s-u — APPROVED** [review]
Thanks!

**Comment by aoles** [comment]
Thanks for your fix @jeroen!

@s-u could you maybe give me a quick update on the timeline of releasing version 0.1-6 on CRAN? Current version 0.1-5 crashes under i386 when reading certain files, which leads to some issues in the downstream package EBImage. Because of the upcoming BioC release it would be really great if this could be sorted out. Cheers!

**Comment by mtmorgan** [comment]
@s-u is this in a Windows build? It breaks release versions of Bioconductor packages such as EBImage.

**Comment by s-u** [comment]
Yes, it was submitted to CRAN. Please ask Uwe if has not updated it yet.

**Comment by jeroen** [comment]
@s-u looks like it [was rejected by the bot](https://win-builder.r-project.org/incoming_pretest/tiff_0.1-6_20201022_055409/Debian/00check.log) due to this:

```
Maintainer: ‘Simon Urbanek <Simon.Urbanek@r-project.org>’

The Title field should be in title case. Current version is:
‘Read and write TIFF images’
In title case that is:
‘Read and Write TIFF Images’

The Description field should not start with the package name,
  'This package' or similar.
```

Here is a [simple fix](https://github.com/s-u/tiff/pull/9). Then the next submission will be auto-approved by the CRAN bot, without action required from Uwe.

**Comment by jeroen** [comment]
@s-u can you please consider [this pr](https://github.com/s-u/tiff/pull/9). Then it will be auto-approved by the CRAN bot, without action from Uwe.

**Comment by jeroen** [comment]
@mtmorgan CRAN has now published the update. Windows binaries should be available within a few days.

**Comment by aoles** [comment]
Thanks a lot @jeroen for all your help!

**Pull request merged**
